name: Land Use Request
description: Suggest integrating a new land use into NZLUSDB
labels: [ "enhancement", "land use request" ]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new land use for NZLUSDB!
        Please fill out the sections below to help us evaluate and integrate your request.
  - type: textarea
    id: land-use-description
    attributes:
      label: Proposed Land Use
      description: |
        Clearly describe the land use you would like to see integrated.
        If a similar land use already exists, explain why a new one is necessary.
    validations:
      required: true
  - type: textarea
    id: lsa-information
    attributes:
      label: Land Suitability Analysis (LSA) Information
      description: |
        Provide any relevant details about the LSA for this land use (e.g., functions, indicators, criteria).
        If available, include examples or previous studies.
  - type: textarea
    id: science-evidences
    attributes:
      label: Scientific Evidence
      description: |
        Share references to scientific literature or previous LSA studies supporting this land use.
        Specify the scope (e.g., functions, criteria) if applicable.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Please indicate how you would like to contribute to this request.
      options:
        - label: I can help find scientific references if needed.
        - label: I would be willing/able to open a Pull Request to contribute this land use.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow NZLUSDB's
        [Code of Conduct](https://nzlusdb.readthedocs.io/en/latest/community/code_of_conduct.html).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
