name: Land Use Modification
description: Suggest a modification to an existing land use in NZLUSDB
labels: [ "enhancement", "land use modification" ]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new land use for NZLUSDB!
        Please fill out the sections below to help us evaluate and implement your proposal
  - type: input
    id: land-use-name
    attributes:
      label: Land Use Name
      description: Please specify the name of the land use you would like to update.
    validations:
      required: true
  - type: textarea
    id: modif-description
    attributes:
      label: Proposed Modification(s)
      description: |
        Clearly describe the changes you are suggesting for this land use.
        Explain why these changes are necessary or beneficial.
    validations:
      required: true
  - type: textarea
    id: potential-solution
    attributes:
      label: Potential Solution
      description: |
        Describe the specific solution or modifications you'd like to see implemented.
        Include examples or references if possible.
  - type: textarea
    id: science-evidences
    attributes:
      label: Scientific Evidence
      description: |
        Provide references to scientific literature, studies, or data that support your proposed modification(s).
        Specify the scope (e.g., functions, criteria) if applicable.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing the proposed modification(s)?
      options:
        - label: I would be willing/able to open a Pull Request to address the mentioned modification(s).
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow NZLUSDB's
        [Code of Conduct](https://nzlusdb.readthedocs.io/en/latest/community/code_of_conduct.html).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
